name: mt_mvae
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pytorch=1.11.0
  - cudatoolkit=11.3
  - torchvision=0.12.0
  - tensorflow=2.6.0
  - tensorboardx=2.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - matplotlib=3.5.3
  - pandas=1.4.1
  - imageio=2.19.2
  - wandb=0.12.16
  - plotly=5.8.0
