#!/bin/bash

bsub -n 8 -W 14:00 -R "rusage[mem=2048,scratch=2048,ngpus_excl_p=1]" -J "mt_mvae_joraml_poe_var_offset_annealing[1-8]" -o mmnist_poe_var_offset_annealing%J_id%I.out <  job_mmnist_poe_var_offset_annealing
